### PR TITLE
Adding Run Task on CloudFoundry

### PR DESCRIPTION
**Pull request by bigorangemachine**
Just adding the ability to run tasks on cloud foundry on deploy.

### CODE REVIEW

**Comment by patrickcrocker** [comment]
This looks good so far.  The main thing missing is a test case.  Do you have a sample application to test tasks?

**Comment by bigorangemachine** [comment]
@patrickcrocker I tested it on my CF instance.  I did take a look at the tests but it wasn't clear how I do a bash unit tests.  Could you clarify how I run run the tests

**Comment by patrickcrocker** [comment]
You add your test to the `itest/put.sh` file.  I can help with this.  What I need help with is the sample application you are using for testing.  Is it a sample app that you can share?

**Comment by bigorangemachine** [comment]
Sorry for the delayed response.

The sample app is behind a walled garden that I cannot share.  However if you setup a run task as simple as `echo "HELLO WORLD"` you'll see that in the CF logs.

The sample in the readme I followed from [their own example indicated here](http://cli.cloudfoundry.org/en-US/cf/run-task.html).  But basically if you have node bundle pack you could run a simple help or version request.

`npm --version` or `node --version`

**Comment by bigorangemachine** [comment]
After attempting to write the test; I realize there isn't a way to do an assertion.  The task runs asynchronous and you can't check the status of the task based how its currently implemented.

If issues/19 was built out we could check the logs for the assertion

**Comment by bigorangemachine** [comment]
@patrickcrocker any thoughts? ⬆️

**Comment by patrickcrocker** [comment]
It looks like the v3 apis have a bit more support for looking at tasks:
http://v3-apidocs.cloudfoundry.org/version/3.39.0/index.html#get-a-task

Is there a sample application available anywhere that you've seen that we can use to start writing a test case around?

**Comment by bigorangemachine** [comment]
Sorry @patrickcrocker,
Like I said before the app I built is in a private repo and I can't share it.

This is what I basically implemented
```
resource_types:
  - name: cf-cli-resource
    type: docker-image
    source:
      repository: bigorangemachine/cf-cli-resource
      tag: latest


resources:
  - name: project-app-server
    type: git
    source:
      uri: git@github.com:username/project-app-server
      branch: develop
      private_key: ((github-private-key))
  - name: cf-env
    type: cf-cli-resource
    source:
      api: https://api.example.com
      username: ((cf-username))
      password: ((cf-password))
      organization: ((cf-org))
      space: ((cf-dev-space))
  - name: cf-dev-server
    type: cf
    source:
      api: https://api.example.com
      username: ((cf-username))
      password: ((cf-password))
      organization: ((cf-org))
      space: ((cf-dev-space))

jobs:
  - name: deploy-cf-dev-server
    plan:
      - get: project-app-server
        trigger: true
      - put: cf-dev-server
        params:
          manifest: project-app-server/manifest_dev.yml
          path: project-app-server
          current_app_name: dev-project-app-server
          environment_variables:
            NODE_ENV: development
            NPM_CONFIG_PRODUCTION: "false"
      # what my project did (node buildpacks & sequelize migrations)
      - put: cf-env
        params:
          command: run-task
          app_name: dev-project-app-server
          task: npm run db:migrate; npm run db:seed
      # basic test with the node buildpacks
      - put: cf-env
        params:
          command: run-task
          app_name: dev-project-app-server
          task: echo "PROJECT DEPLOYED"
```

That API call is a good lead on building a good way of verifying the a task ran.  When I get a chance I'll see what I can do

**Comment by patrickcrocker** [comment]
This has been implemented in v2.5.0/latest!

FYI, I made a bunch of changes over the weekend to clean up some code, so i didn't directly merge your PR because of the conflicts.

**Pull request closed without merging**
